loginfo:
    loglevel: debug
    logpath: ./watchman.log
    maxage: 15
    maxsize: 20
    servicename: mabowatchman
mqttinfo:
    host: 59.110.157.60
    password: TyinD@444b
    port: 1883
    pubtopic: sy/smt/filewatch
    qos: 0
    username: client001
records:
    - file: G:\2025\test\abc.txt
      column: 10
udpinfo:
    host: 127.0.0.1
    port: 60000
watchman:
    deviceid: "55030304593"
    devicename: TestDevice
    filelist:
        - abc.txt
    path: G:\\2025\\test
    startcolumn: 0
    suffix:
        - txt
        - log
    transfermethod: mqtt
    watchall: false
