loginfo:
  loglevel: debug
  logpath: ./watchman.log
  maxage: 15
  maxsize: 20
  servicename: mabowatchman
records:
- file: D:\GoPrj\abc\abc.txt
  column: 32
- file: add.txt
  column: 1
- file: D:\GoPrj\abc\aaane.txt
  column: 2
udpinfo:
  host: 127.0.0.1
  port: 60000
watchman:
  filelist:
  - abc.txt
  - efg.txt
  path: D:\\GoPrj\\abc
  startcolumn: 0
  transfermethod: udp
  watchall: true
