loginfo:
    loglevel: debug
    logpath: ./watchman.log
    maxage: 15
    maxsize: 20
    servicename: mabowatchman
mqttinfo:
    host: 110.0.0.10
    password: aaadkeifkd
    port: 1883
    pubtopic: test
    qos: 0
    username: watchman01
records:
udpinfo:
    host: 127.0.0.1
    port: 60000
watchman:
    filelist:
    path: D:\Test
    startcolumn: 0
    suffix:
        - txt
        - log
    transfermethod: udp
    watchall: true
